### ISSUE TITLE
Patch List(offset and vale) From Text File

### ISSUE THREAD

**Issue by sudhanshu947** [mbwilding/PacketTracerConfigUnlock#1]
Hey can you please add option to add offset and value from text file so we wont need to compile for every software or pleas guide i had tried to create but am not able to

**Comment by mbwilding** [comment]
I can do that. I will make it take a config file.

**Comment by mbwilding** [comment]
Edited BinaryDifference and BinaryPatcher to export/support YML files. If there is only one patch file it won't produce a menu, if there are multiple, it will ask you to select. YML files need to be in the same directory as the EXE.
Removed the release builds, so will just have to build yourself with .NET 7 which is pretty easy.

The YAML stores the addresses as decimal not hex, but should be transparent from the user as both Patcher and Difference understand it.

**Comment by sudhanshu947** [comment]
Thanks sir can you guide me to setup on winforms app

**Comment by mbwilding** [comment]
The point of this patcher is to be platform agnostic, using WinForms ties it to the windows platform.

Will eventually be making BinaryDifference not rely on WPF, will probably use an agnostic UI framework.

**Comment by sudhanshu947** [comment]
Thanks for you response sir i had created it if i will face issue will ask
you.
Thanks for your precious time.
